Worlds:
  world:
    - place
    - break
  world_nether:
    - place
    - break
  world_the_end:
    - place
    - break
messages:
    noCommandPermission: "&4You do not have permission to perform the command &6%command%"
    noConsole: "&4You can only run this command in game"
    noBreaking: "&4You do not have permission to break blocks in world &6%world%"
    noPlaceing: "&4You do not have permission to place blocks in the world &6%world%"
    reload: "&aYou have successfully reloaded antibreaking"
    invalidArgs: "&4You must pass either &6on&4 or &6off&4 world name is optional"
    breakCmd: "&aTou have successfully set &6%world%&a block breaking to &6%arg%"
    placeCmd: "&aTou have successfully set &6%world%&a block placing to &6%arg%"

